name: lint
on: [ push ]

jobs:
    frontend-lint:
      name: lint
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v2
        - uses: actions/setup-node@v1
        - run: ./wizard.sh -a